Adding panic-handling
uber/cadence pull request #5075
Opened 2023-02-06 05:15 UTC by davidporter-id-au

## Context 
As a follow-up to the panic [here](https://github.com/uber/cadence/pull/5074) I'm keen to see that uncaught panics don't cause instability. So with a small refactor, adding a recovery to the replication daemon here. 

## Testing
Unit-testing

2023-02-07 00:44 UTC, davidporter-id-au commented on service/history/replication/task_processor.go
> +		e := recover()
this is the only addition, apart from the refactoring

2023-02-09 21:51 UTC, Groxx requested changes
minor but important change needed, otherwise LGTM and yay fewer `goto`s!

2023-02-09 21:53 UTC, davidporter-id-au commented on service/history/replication/task_processor.go
> +		return false
good catch

2023-02-09 21:57 UTC, davidporter-id-au commented on service/history/replication/task_processor.go
> +		return false
urgh... I did something dumb and I thought this changed already

2023-02-09 22:24 UTC, Groxx commented on service/history/replication/task_processor.go
> +			return true
```suggestion
			return false
```
I think?  I believe this changed since the last round

2023-02-09 22:25 UTC, Groxx commented on service/history/replication/task_processor.go
> +	return false
ah, actually, should this be true too?
```suggestion
	return true
```

2023-03-13 19:42 UTC, closed without merging