Add tests for transfer_queue_processor.go
uber/cadence pull request #6483
Opened 2024-11-06 18:54 UTC by fimanishi

**What changed?**
Added tests for transfer_queue_processor.go

**Why?**
Code coverage

**How did you test it?**
Unit tests

**Potential risks**

**Release notes**

**Documentation Changes**

2024-11-07 12:32 UTC, 3vilhamster commented on service/history/queue/transfer_queue_processor_test.go
> +	transferQueueProcessorSuite struct {
Please avoid introducing new suites. As far as I understand, we generally agree that suites are not very useful, and you can achieve the same with one function that will prepare the object and mocks.

goleak.VerifyNone could be switched to VerifyTestMain and put into TestMain of the package.

2024-11-07 12:34 UTC, 3vilhamster requested changes
Let's not introduce new suites in tests.
It should be fine for existing suites, but all new parts should be tested as individual tests with a table-test structure where suitable.

2024-11-07 21:44 UTC, taylanisikdemir approved these changes

2024-11-08 09:55 UTC, 3vilhamster approved these changes

2024-11-12 01:13 UTC, merged